name: First Workflow
on: workflow_dispatch # manually triggers the workflow by the user
jobs:
  first-job: # Not reserverd - Name of the Job
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - bye!"
